implement mark as read feature
aceTmobile/web-ui-developer-puzzle pull request #4
Opened 2021-08-27 17:48 UTC by aceTmobile

- allow user to mark a book as finished from the reading list side nav
- Indicate the book as finished in the side nav, including the finished date.
- user can still remove the book from their reading list. Removing a book will reset the finished status (i.e. if they add the book back it will not be finished).
- The Want to Read button should change to Finished.
- e2e test implemented

2021-08-31 18:46 UTC, mandarini requested changes
Please fix the issues here!

2021-08-31 18:46 UTC, mandarini commented on libs/api/books/src/lib/reading-list.service.ts
> +    this.storage.update(list => list.map(item => item.bookId == id
Linting error here! Please make sure `npm run lint` passes

2021-08-31 18:46 UTC, mandarini commented on libs/books/feature/src/lib/reading-list/reading-list.component.html
> +        finished: {{ b.finishedDate }}
Please make sure this date is in a human-readable format!

2021-08-31 23:22 UTC, aceTmobile commented
@mandarini Hi, I made corrections. The mr should be good to go now. Please re-review. thanks

2021-09-09 07:16 UTC, mandarini commented
Thanks! You're done!

2021-09-30 09:47 UTC, merged